### ISSUE TITLE
vit_base_patch32_224 instead of vit_base_patch16_384

### ISSUE THREAD

**Issue by 0xrushi** [antocad/FocusOnDepth#12]
Hi,

Instead of vit_base_patch16_384, I'm trying to use vit_base_patch32_224 in the segmentation branch. 
I did change 

"patch_size":32 and 

"transforms":{
            "resize":224,
            "p_flip":0.5,
            "p_crop":0.3,
            "p_rot":0.2
        },
But its crashing for some reason. Do you know what else need to be changed in the config?

**Comment by rushic24** [comment]
My bad, I think the paper didn't implement other patch sizes
