### ISSUE TITLE
depth 

### ISSUE THREAD

**Issue by andy500** [antocad/FocusOnDepth#14]
can not change to type depth in conifig as will no work  get this error  RuntimeError: Error(s) in loading state_dict for FocusOnDepth:
        Unexpected key(s) in state_dict: "head_segmentation.head.0.weight", "head_segmentation.head.0.bias", "head_segmentation.head.2.weight", "head_segmentation.head.2.bias", "head_segmentation.head.4.weight", "head_segmentation.head.4.bias". why only work in type full

**Comment by KhuongDiep911** [comment]
Hi, 

I have the same problem with you. did you solve the problem? If so, can you show me how to solve it?

Thank you in advance
Khuong

**Comment by KhuongDiep911** [comment]
Hi Andy,

Can I ask you what is the deep scanner you are using. Can you give me the github repo link.

Thank you
Khuong

**Comment by andy500** [comment]
IT IS A PLUGIN FOR AFTER EFFECTS NOT A GITHUB CODE IT CREATES DEPTH MAPS
AND IS GOOD

**Comment by antocad** [comment]
Hi, just a quick answer: the pre-trained weights given are only working with type='full'.
We didn't pre-train for depth-specific tasks.
However, you can still use type='full' and, after the forward pass you only use out_depth.

**Comment by andy500** [comment]
Thank you for the clarification.

**Comment by KhuongDiep911** [comment]
Thank you for Andy and Antocad for your kind response!
