### ISSUE TITLE
A question about depth estimation accuracy .

### ISSUE THREAD

**Issue by jck520** [antocad/FocusOnDepth#2]
Could you provide a pre-trained model, or we train the network from scratch, and finally achieve a depth estimation result comparable to DPT? Looking forward to your reply, thank you！

**Comment by younesbelkada** [comment]
hi there, 
thanks for your message, in this repository you can either train from scratch or download our pre-trained model. Please carefully follow the instructions on the ```README``` or the [config wiki](https://github.com/antocad/FocusOnDepth/wiki/Config-Wiki) to understand more

**Comment by younesbelkada** [comment]
Closing this issue for now, please feel free to reopen it if you have any queries
