### ISSUE TITLE
No need for depth aspect

### ISSUE THREAD

**Issue by SJayYang** [antocad/FocusOnDepth#26]
Hi, 

I'm only interested in using the FOD model for semantic segmentation - how should I approach curating the depth aspect of the dataset? Should I just use segmentation masks for both the depth and segmentation masks of the dataset? Or is there a way to remove that aspect of the output head?

**Comment by antocad** [comment]
Hello, there is a branch named "segmentation_only"; however it was created for a specific use-case, maybe you will have to slightly change the code.
