### ISSUE TITLE
Training loss and log

### ISSUE THREAD

**Issue by jiaqixuac** [antocad/FocusOnDepth#5]
Hi,

Thanks for the nice repo.
I wonder if you can provide the training log.
And if you are going to use the median + mae which is used in MiDaS-v2
https://github.com/isl-org/MiDaS/issues/28

Thanks!

**Comment by younesbelkada** [comment]
Hi,

Thank you very much for your message. You can find the logs of the training [here](https://wandb.ai/younesbelkada/FocusOnDepth?workspace=user-younesbelkada) for the ViT large and ViT base backbone
For now we are only using Scale and Shift loss that is provided in the original repo, if you plan to use this specific loss you can submit a PR and we will review it
Thanks
