### ISSUE TITLE
Amazing!! Will the same weights work for "type":"segmentation" ?

### ISSUE THREAD

**Issue by rushic24** [antocad/FocusOnDepth#7]
I don't have a dataset with depth, so I want to train only segmentation. I'm confused, will this same architecture work?

**Comment by younesbelkada** [comment]
Hi! Yes it should, just change the ```type``` argument on the config file to ```segmentation```. Let me know if it does not work!

**Comment by rushic24** [comment]
I think there are multiple places where that type isn't taken into consideration

I added this in dataset.py
```
if config['General']['type'] == "full" or config['General']['type'] == "depth":
            assert (len(self.paths_images) == len(self.paths_depths)), "Different number of instances between the input and the depth maps"
```

But now traindataloader also needs to handle that
![image](https://user-images.githubusercontent.com/6279035/162463268-28a0a7da-bf44-42df-9830-cb971fb13d56.png)

**Comment by younesbelkada** [comment]
it looks like there might be a problem on the structure of your folder, could you send me the structure of your working folder?

**Comment by antocad** [comment]
Hi, if you want to use this model only for segmentation, and if you don't have any depth data (our master branch is not very well adapted to this), you can just use the segmentation-only branch.
There are juste little modifications in the config file to bring in addition, but it should solve your issue.

**Comment by rushic24** [comment]
Wow that works thanks,

Do you know if this model can segment the fine details with some more tweaks?

![image](https://user-images.githubusercontent.com/6279035/162636718-cb91c3b3-ba07-4e3f-ab74-a89e1e5adfe4.png)
![image](https://user-images.githubusercontent.com/6279035/162636739-91c9c119-6878-45e7-a1a6-1dc0a604018f.png)
