### ISSUE TITLE
How to add IOU score?

### ISSUE THREAD

**Issue by rushic24** [antocad/FocusOnDepth#8]
Hi
I'm currently using the below function to calculate IOU score (for binary segmentation). But that doesn't seem to give a consistent increase in IOU score as epochs increase. I was wondering if it was correct.

```
def iou_pytorch(outputs: torch.Tensor, labels: torch.Tensor):
    return torch.sum(outputs & labels)/torch.sum(outputs | labels)
```

Thanks

**Comment by younesbelkada** [comment]
Hey,
Thank you for your comment! Actually there is a very nice library called ```torchmetrics``` (```pip install torchmetrics```) that you can use for this sake juste to be sure that everything is correct, I have wrote to you a small snippet of code to show how it works:
```
import torchmetrics
import torch

metric = torchmetrics.IoU(num_classes=2) # binary segmentation

def test_iou(N):
    for i in range(N):
        preds = torch.randn(2, 256, 256).argmax(dim=0)
        targets = torch.randint(0, 1, (1, 256, 256))
        iou = metric(preds, targets)
        print("IoU on step {}: {}".format(i, iou))
    acc = metric.compute()
    print("IoU on all steps: {}".format(acc))

if __name__ == '__main__':
    test_iou(10)
```
Then you can compare the results of torchmetric's IoU with yours to see if your implementation is correct!
Let me know if anything is unclear

**Comment by rushic24** [comment]
BTW that IoU has now changed to JaccardIndex. Just noting it here if someone comes across same issue.
